---

- name: Create usr mastodon
  hosts: all
  tasks:
      #Ajoute l'utilisateur mastodon avec pas de mdp
    - name: Adding user mastodon
      user: 
        name: mastodon 
        group: sudo
        shell: /bin/bash
        password: ''
